spring:
  profiles:
    active: test
  config:
    import: optional:configserver:http://localhost:8888

my.greeting: Hello
app:
  name: My App
  description: ${app.name} description
list.values: One, Two, Three
db_map.values: "{connectionString: 'http://__', userName: 'foo', password: 'pass'}"

# @ConfigurationProperties annotated Configuration class will look up props starting with 'db'
db:
  connection: "{connectionstring:'http://url__', userName:'foo', password:'pass'}"
  host: 127.0.0.1
  port: 1200

management.endpoints.web.exposure.include: "*"